import { type Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css';
import { SidebarProvider } from "@/components/ui/sidebar"
import { DirectoryContextProvider } from '@/context/DirectoryContext';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Clerk Next.js Quickstart',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
			<SidebarProvider>
				<DirectoryContextProvider>
					<html lang="en">
						<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
							{children}
						</body>
					</html>
				</DirectoryContextProvider>
			</SidebarProvider>
		</ClerkProvider>
	)
}
		